### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by pahrizal** [LombokAcademy/todo-app#1]
Update readme with relevant context of this repo,
WHAT is this repo about?
How to setup this repo in local development machine?

**Comment by iamCelott** [comment]
bang bagian yang
"How to setup this repo in local development machine?"
itu maksud nya bagaimana cara biar repo ini bisa di copt komputer/laptop atau bagaimana cara nge run nya?

**Comment by juhan26** [comment]
bang, updatenya secara kesuluruhan atau di tambah ?

**Comment by pahrizal** [comment]
Update keseluruhan nya. Jadi bawaan nya template di hapus semua. Sent from my iPhoneOn 23 Jan 2024, at 11:01 pm, juhan26 ***@***.***> wrote:﻿
bang, updatenya secara kesuluruhan atau di tambah ?
