### ISSUE TITLE
[DB] create `User` model

### ISSUE THREAD

**Issue by pahrizal** [LombokAcademy/todo-app#16]
ORM we call a table with `Model` term. Now, create a model called `User` with these requirements:

- [ ] create model in `src/backend/database/user.model.js`
- [ ] this user model/table should have these column: 
  - `id`,  the user id represented with UUID. type: `STRING`
  - `username`, the username for user to login with. type: `STRING`
  - `password`, the password for user. this should be hashed using MD5 or something stronger. type: `STRING`
  - `fullname`, the full name of user. type: `STRING`

[follow this documentation](https://sequelize.org/docs/v6/core-concepts/model-basics/#using-sequelizedefine) on how to create a model in sequelize

**Comment by iamCelott** [comment]
Sir, will each model be separated into its own file, like
- user.model.js
- task.model.js
- history.model.js

**Comment by pahrizal** [comment]
> Sir, will each model be separated into its own file, like
> 
> * user.model.js
> * task.model.js
> * history.model.js

yes, that's right! but for this issue you only work on `User` model. don't combine them here
