### ISSUE TITLE
Initialize backend code

### ISSUE THREAD

**Issue by pahrizal** [LombokAcademy/todo-app#2]
Install dependencies that we need for backend.  we will create a REST API using `express`

**Comment by juhan26** [comment]
sir, is the installation of body-parser / cors required for this?

**Comment by pahrizal** [comment]
> sir, is the installation of body-parser / cors required for this?

yes, you should install the `body-parser` and `cors` package . this two packages is already built-in in `express` package. so you don't need to install it separately

**Comment by juhan26** [comment]
> > sir, is the installation of body-parser / cors required for this?
> 
> yes, you should install the `body-parser` and `cors` package . this two packages is already built-in in `express` package. so you don't need to install it separately

okay sir..
