### ISSUE TITLE
Create `/api/hello` endpoint

### ISSUE THREAD

**Issue by pahrizal** [LombokAcademy/todo-app#3]
create  initial  `/api/hello` GET route endpoint. this will return HTTP 200 with JSON payload:
```JSON
{
   "message": "hello world!"
}
```

project file structure for backend will be like below:
```
src/
  backend/
    api/
      hello/
        controller.js
        route.js
        index.js
  index.js
```

`src/backend/api/hello/controller.js`, will be responsible for handling request and response. e.g:
```javascript
module.exports = {
  get: (req, res, next) => {
    const data = { message: "hello world!" };
    res.send(data);
  }
}
```

`src/backend/api/hello/route.js`, will be responsible for managing endpoint route. e.g:
```javascript
const express = require('express');
const controller = require('./controller');
const router = express.Router();

router.get( '/hello', controller.get );

module.exports = router;
```

`src/backend/api/hello/index.js`, the entrypoint for this `hello` endpoint. this file will exporting controller and route. e.g:
```javascript
module.exports = {
  controller: require('./controller'),
  router: require('./route.js')
}
```

after that, we can initialize this route endpoint in `src/backend/index.js`:
```javascript
const helloRoute = require('./api/hello')
app.use( "/api", [ helloRoute ] );
```

**Comment by juhan26** [comment]
sir, what makes the difference between the index inside and outside?

**Comment by pahrizal** [comment]
An `index.js` is an entrypoint of folder that we can use to export. This is a best practice in managing multiple module in javascript
