### ISSUE TITLE
Create Docker Compose file for database

### ISSUE THREAD

**Issue by pahrizal** [LombokAcademy/todo-app#7]
create `docker-compose.yaml` in root project directory to spin mariadb database with this env:
```shell
MARIADB_ROOT_PASSWORD=S3cret!
MARIADB_DATABASE=todo
MARIADB_USER=todo
MARIADB_PASSWORD=todo
```
container name: `todo-db`
volume: `todo-db`

**Comment by juhan26** [comment]
sir, is the docker-compose.yaml file that we create ourselves, or is it already included with docker?

**Comment by pahrizal** [comment]
> sir, is the docker-compose.yaml file that we create ourselves, or is it already included with docker?

we create this file and define the content according to what service we need. for now, we only need a database service

**Comment by iamCelott** [comment]
sir is MARIADB_ROOT_PASSWORD was "S3cret!" or a secret password that only we know

**Comment by pahrizal** [comment]
> sir is MARIADB_ROOT_PASSWORD was "S3cret!" or a secret password that only we know

Make it `S3cret!`
