### ISSUE TITLE
[UI] design a simple UI for the app

### ISSUE THREAD

**Issue by pahrizal** [LombokAcademy/todo-app#9]
think about how google design their search UI, they think more about functionality and simplicity to achieve a goal for someone who need to search something just need to type it. 

Google show the UI only if the user need it. let say, when we go to google.com, they know that we want to search something, so they show only an input text box that we can type what we are going to search, then click the search button.

I hope you can get the idea.

**Comment by DirwaVIP** [comment]
https://www.figma.com/file/EY2k5vJOPTuN1B6c1dVCLm/Untitled?type=design&node-id=0%3A1&mode=design&t=KlohwBkH1H7OtHD7-1

This is the design you requested, I used figma to make it, I hope you like the design I made

**Comment by pahrizal** [comment]
@DirwaVIP thanks for the design. I am sorry, I think I explaining it wrong. yes we should follow the simplicity google design their search engine UI, but we should design it with our app requirements as  TODO APP.

you can do some research on "todo app UI design" in dribble or pinterest maybe to get started with your own design.

**Comment by pahrizal** [comment]
@DirwaVIP make the UI design like this one:
![image](https://github.com/LombokAcademy/todo-app/assets/36581242/8f843521-1554-48e2-9c0d-1f657f5647bf)

**Comment by DirwaVIP** [comment]
okay, maybe what you mean is making a search design for the todo app, sorry for the misunderstanding, I will continue to learn from my mistakes and become even better, thank you for the criticism and suggestions

**Comment by DirwaVIP** [comment]
@pahrizal This is the project, I hope it matches what you asked for, if there is something missing or not suitable, you can give me criticism and suggestions, I hope it helps, thank you

https://www.figma.com/file/uanLajEWX8LbTWLCVWgXUJ/Untitled?type=design&node-id=0%3A1&mode=design&t=O2tmztfTITwHOsG6-1

I was inspired by the Todoist application

**Comment by pahrizal** [comment]
nice work @DirwaVIP . that's a good design!. can you update our `README.md` and add the figma link? after updating the `README.md` file, you can create a Pull Request for this issue
